# ----------------
# Split por cable TRRS
# ----------------
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE=n

# ----------------
# USB ONLY (sin BLE)
# ----------------
CONFIG_ZMK_USB=y
CONFIG_BT=n
CONFIG_ZMK_BLE=n

# ----------------
# Pantallas OLED
# ----------------
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y

# ----------------
# RGB Underglow (WS2812)
# ----------------
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# ----------------
# Power management
# ----------------
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000